version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      context: https://github.com/vitalyBorisov/nginx.git
      dockerfile: Dockerfile
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.prod
      context: '.'
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      - NODE_ENV=production
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: https://github.com/vitalyBorisov/intspirit-crm-client.git
      dockerfile: Dockerfile.prod
    volumes:
      - /app/node_modules
      - client:/app

volumes:
  client:
